version: 1.0.{build}
environment:
  matrix:
    - ANDROID_HOME: "C:\\android-sdk-windows"
install:
  - set OLD_PATH=%PATH%
  - set PATH=C:\msys64\usr\bin
  - yes | C:\msys64\usr\bin\pacman --sync ccache
  - set PATH=%OLD_PATH%
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip
  - 7z x sdk-tools-windows-3859397.zip -oC:\android-sdk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses > nul
build_script:
  - gradlew.bat assemble
test_script:
  - gradlew.bat test
